test_index.FrontEndHomePageTest.test_selling_validate
----------------------------------------------------
Last Page: http://localhost:8081/
  Browser: chrome
Timestamp: 1605781351  (Unix Timestamp)
     Date: Thursday, November 19, 2020
     Time: 5:22:31 AM  (동부 일광 절약 시간, UTC-05:00)
----------------------------------------------------
Traceback: File "c:\users\user\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\user\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\user\appdata\local\programs\python\python38\lib\unittest\mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\user\CISC-327-Course-Project\qa327_test\R3\test_index.py", line 355, in test_selling_validate
    self.assert_element("#update", value="Sell")
Exception: assert_element() got an unexpected keyword argument 'value'